site_name: AmitTech
site_url: https://amitpinchasi.github.io/amittech/
docs_dir: docs
site_dir: site

theme:
  name: material
  logo: amittech.png
  favicon: amittech.png
  direction: rtl
  language: he
  palette:
    - scheme: slate
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: מצב בהיר
    - scheme: default
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: מצב כהה
  font:
    text: Heebo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy

plugins:
  - search:
      lang: he
  - roamlinks
  - awesome-pages
  - exclude:
      glob:
        - "*.pdf"

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css
