/* Illustration player: play / pause / restart controls for the animated
   illustration SVGs (docs/images/illustrations, generated by
   scripts/illustrate). As a plain <img> they start looping the moment the
   page loads, so by the time a reader scrolls down to one it is somewhere
   in the middle of a cycle and out of step with the text around it - and an
   <img> cannot be paused or restarted from the page.

   Each animated one is fetched and inlined into a shadow root (its CSS, ids
   and keyframe names stay scoped to it, so several on one page don't
   collide), starts paused on its first step, and gets a control bar.
   Restart swaps in a fresh copy of the SVG node, which restarts every CSS
   animation in it from zero.

   Anything unexpected - no shadow DOM, a failed fetch, an SVG this doesn't
   recognise - leaves the original <img> in place, which still animates as
   before. Readers with prefers-reduced-motion keep the <img> too: the SVG
   already shows its final state statically for them. */
(function () {
  'use strict';

  var SRC_RE = /\/images\/illustrations\/[^\/?#]+\.svg(?:[?#]|$)/;
  var DARK_MEDIA_RE = /@media\s*\(\s*prefers-color-scheme\s*:\s*dark\s*\)\s*\{((?:[^{}]*\{[^{}]*\})*)\s*\}/g;
  var DURATION_RE = /animation-duration\s*:\s*([\d.]+)s/;

  var ICONS = {
    play: 'M8,5.14V19.14L19,12.14L8,5.14Z',
    pause: 'M14,19H18V5H14M6,19H10V5H6V19Z',
    restart: 'M12,5V1L7,6L12,11V7A6,6 0 0,1 18,13A6,6 0 0,1 12,19A6,6 0 0,1 6,13H4A8,8 0 0,0 12,21A8,8 0 0,0 20,13A8,8 0 0,0 12,5Z'
  };

  var LABELS = {
    play: 'הפעלה',
    pause: 'השהיה',
    playAria: 'הפעלת האנימציה',
    pauseAria: 'השהיית האנימציה',
    restartAria: 'הפעלה מחדש מההתחלה'
  };

  // Styles for the player chrome inside each shadow root. Site colour
  // variables inherit through the shadow boundary, so the controls follow
  // whichever theme is active. Class names are prefixed so they can't meet
  // the illustration's own (.t, .code, .edge, ...).
  var CHROME_CSS =
    ':host{display:inline-block;max-width:100%;vertical-align:middle;}' +
    '.ip-stage{cursor:pointer;line-height:0;}' +
    '.ip-stage>svg{display:block;max-width:100%;height:auto;}' +
    ':host(.ip-paused) .ip-stage>svg,:host(.ip-paused) .ip-stage>svg *,' +
    ':host(.ip-paused) .ip-fill{animation-play-state:paused !important;}' +
    '.ip-bar{display:flex;align-items:center;gap:8px;margin-top:6px;direction:rtl;' +
      'font-family:inherit;font-size:13px;line-height:1;}' +
    '.ip-btn{display:inline-flex;align-items:center;gap:4px;height:28px;padding:0 10px;' +
      'border:1px solid var(--am-border,rgba(127,127,127,.35));border-radius:14px;' +
      'background:transparent;color:var(--md-default-fg-color,currentColor);' +
      'font:inherit;cursor:pointer;flex:none;}' +
    '.ip-btn:hover{border-color:var(--md-accent-fg-color,#4361ee);color:var(--md-accent-fg-color,#4361ee);}' +
    '.ip-btn:focus-visible{outline:2px solid var(--md-accent-fg-color,#4361ee);outline-offset:2px;}' +
    '.ip-btn svg{width:16px;height:16px;fill:currentColor;flex:none;}' +
    '.ip-btn.ip-icon{width:28px;padding:0;justify-content:center;}' +
    '.ip-track{flex:1;min-width:24px;height:3px;border-radius:2px;overflow:hidden;' +
      'background:var(--am-border,rgba(127,127,127,.3));}' +
    '.ip-fill{height:100%;background:var(--md-accent-fg-color,#4361ee);transform-origin:right;' +
      'animation:ip-progress var(--ip-duration) linear infinite;}' +
    '@keyframes ip-progress{from{transform:scaleX(0);}to{transform:scaleX(1);}}' +
    '@media print{.ip-bar{display:none;}}';

  function supported() {
    return !!(Element.prototype.attachShadow && window.fetch && window.DOMParser &&
      !(window.matchMedia && matchMedia('(prefers-reduced-motion: reduce)').matches));
  }

  function icon(name) {
    return '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="' + ICONS[name] + '"/></svg>';
  }

  // The illustrations pick their palette with @media (prefers-color-scheme).
  // As an <img> that query follows the used color-scheme of the <img>
  // element, i.e. the site theme (Material sets color-scheme per scheme).
  // Inline, it would follow the OS instead, so the dark block is rewritten
  // to hang off a host class that mirrors the <img> behaviour.
  function scopeDarkPalette(css) {
    return css.replace(DARK_MEDIA_RE, function (_, rules) {
      return rules.replace(/(^|\})\s*([^{}]+)\{/g, function (m, close, selectors) {
        return close + selectors.split(',').map(function (s) {
          return ':host(.ip-dark) ' + s.trim();
        }).join(',') + '{';
      });
    });
  }

  function prefersDark(el) {
    var cs = getComputedStyle(el).colorScheme || '';
    var dark = /\bdark\b/.test(cs), light = /\blight\b/.test(cs);
    if (dark !== light) return dark;
    return !!(window.matchMedia && matchMedia('(prefers-color-scheme: dark)').matches);
  }

  var players = [];

  function syncThemes() {
    players.forEach(function (host) {
      host.classList.toggle('ip-dark', prefersDark(host));
    });
  }

  function buildPlayer(img, svgText) {
    var doc = new DOMParser().parseFromString(svgText, 'image/svg+xml');
    var svg = doc.documentElement;
    if (!svg || svg.nodeName.toLowerCase() !== 'svg' || doc.getElementsByTagName('parsererror').length) return;
    var style = svg.querySelector('style');
    if (!style || style.textContent.indexOf('@keyframes') === -1) return;

    var css = style.textContent;
    if (/prefers-color-scheme/.test(css)) {
      css = scopeDarkPalette(css);
      if (/prefers-color-scheme/.test(css)) return; // a shape this doesn't know how to scope
    }
    style.textContent = css;
    var duration = DURATION_RE.exec(css);

    if (img.alt) {
      svg.setAttribute('aria-label', img.alt);
      svg.setAttribute('role', 'img');
    }

    var template = document.importNode(svg, true);
    var host = document.createElement('span');
    host.className = 'illus-player ip-paused';
    var root = host.attachShadow({ mode: 'open' });
    root.innerHTML =
      '<style>' + CHROME_CSS + '</style>' +
      '<div class="ip-stage"></div>' +
      '<div class="ip-bar">' +
        '<button type="button" class="ip-btn ip-toggle"></button>' +
        '<button type="button" class="ip-btn ip-icon ip-restart" aria-label="' + LABELS.restartAria +
          '" title="' + LABELS.restartAria + '">' + icon('restart') + '</button>' +
        '<div class="ip-track"><div class="ip-fill"></div></div>' +
      '</div>';
    host.style.setProperty('--ip-duration', (duration ? duration[1] : '10') + 's');

    var stage = root.querySelector('.ip-stage');
    var toggle = root.querySelector('.ip-toggle');
    var track = root.querySelector('.ip-track');

    function render(playing) {
      host.classList.toggle('ip-paused', !playing);
      var name = playing ? 'pause' : 'play';
      toggle.innerHTML = icon(name) + '<span>' + LABELS[name] + '</span>';
      toggle.setAttribute('aria-label', LABELS[name + 'Aria']);
    }

    function isPlaying() { return !host.classList.contains('ip-paused'); }

    // Fresh nodes get fresh CSS animations, all starting from zero together.
    function reset() {
      stage.textContent = '';
      stage.appendChild(template.cloneNode(true));
      track.innerHTML = '<div class="ip-fill"></div>';
    }

    stage.addEventListener('click', function () { render(!isPlaying()); });
    toggle.addEventListener('click', function () { render(!isPlaying()); });
    root.querySelector('.ip-restart').addEventListener('click', function () {
      reset();
      render(true);
    });

    reset();
    render(false);
    host.classList.toggle('ip-dark', prefersDark(img));
    img.replaceWith(host);
    players.push(host);
  }

  function init() {
    if (!supported()) return;
    var imgs = document.querySelectorAll('.md-typeset img[src]');
    Array.prototype.forEach.call(imgs, function (img) {
      if (!SRC_RE.test(img.getAttribute('src'))) return;
      fetch(img.src)
        .then(function (r) { return r.ok ? r.text() : ''; })
        .then(function (text) { if (text && img.isConnected) buildPlayer(img, text); })
        .catch(function () {});
    });
  }

  if (window.MutationObserver) {
    new MutationObserver(syncThemes).observe(document.documentElement, {
      attributes: true, attributeFilter: ['data-md-color-scheme', 'data-theme', 'style', 'class']
    });
  }
  if (window.matchMedia) {
    var mq = matchMedia('(prefers-color-scheme: dark)');
    if (mq.addEventListener) mq.addEventListener('change', syncThemes);
  }

  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init);
  else init();
})();
